### ISSUE TITLE
Area annotation UNDO/REDO option is missing.

### ISSUE THREAD

**Issue by Salmanshams67** [MedVisBonn/eyelab#3]
* Python version: 3.9

### Description

I was using the EyeLab annotation tool and noticed that the undo/redo functionality is not available for area annotations. While layer annotations can be easily undone and redone, area annotations (which are drawn by marking pixels with a pen) do not support this feature.

This lack of functionality makes it difficult to correct mistakes made during area annotations, as there’s no way to revert to a previous state. I expected that area annotations would have similar undo/redo capabilities as layer annotations for a more user-friendly experience.

@Oli4 @actions-user

**Comment by Oli4** [comment]
Dear @Salmanshams67,

I’m glad to hear that you are finding EyeLab useful in your work! We primarily used the tool for layer annotation. I completely agree that adding redo/undo functionality for area annotations would be a valuable improvement. If you submit a pull request with these changes, I’d be happy to review and include them.

Unfortunately, I’m currently unable to dedicate much time to further developing EyeLab, but I appreciate your contributions to its enhancement.

Best regards,
Olivier

**Comment by Salmanshams67** [comment]
By using "Left click" we can do the drawing, using "Right click" we can erase the drawing.

**Comment by Salmanshams67** [comment]
Resolved.
